config/routes.rb
# frozen_string_literal: true

require 'resque/server'

Rails.application.routes.draw do
  devise_for :users # , ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  mount RootApi => '/'
  mount Resque::Server.new, at: '/resque'

  resources :events do
    resources :items
  end

  get 'events/page/(:page(.:format))', to: 'events#index'

  get :toggle, to: 'locales#toggle'
  get :about, to: 'about#index'
  get :help, to: 'help#index'
  root 'events#index'
end

app/models/event.rb
# frozen_string_literal: true

# == Schema Information
#
# Table name: events
#
#  id          :bigint           not null, primary key
#  content     :text
#  done        :boolean          default(FALSE)
#  finished_at :datetime
#  name        :string
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#  user_id     :bigint
#
# Indexes
#
#  index_events_on_user_id  (user_id)
#
# Foreign Keys
#
#  fk_rails_...  (user_id => users.id)
#
class Event < ApplicationRecord
  belongs_to :user, counter_cache: true
  has_many :items, dependent: :destroy
  has_many :comments, as: :commentable, dependent: :destroy
  has_many :commentators, through: :comments, source: :user
  has_many_attached :files # strict_loading: true

  validates :name, presence: true

  after_create :done_events, -> { user.increment!(done? ? :done_counter : :not_done_counter) }

  private

  def done_events
    user.increment!(done? ? :done_counter : :not_done_counter)
  end

  def not_done_events
    user.decrement!(done? ? :done_counter : :not_done_counter)
  end
end

app/controllers/events_controller.rb
# frozen_string_literal: true

class EventsController < ApplicationController
  include Commentable

  before_action :authenticate_user!
  before_action :set_event, only: %i[show edit update destroy]

  # Отображение всех созданных заданий
  def index
    # Rack::MiniProfiler.step('Загрузка всех событий') do
    #   @all = Event.all
    # end
    @events = policy_scope(Event).includes(:items).page(params[:page]).per(5)
    I18n.locale = session.fetch(:locale, I18n.default_locale).to_sym
  end

  # Просмотр конкретного задания
  def show
    authorize @event
    @comments = @event.comments.root&.self_and_descendants&.order(:lft)
    # @comments = sort_comments(@event.comments.order(:created_at))
  end

  # Формирует и отображает HTML-форму, которая позволяет подготовить данные для создания объекта.
  # @note Вызывается при нажатии по кнопке 'New event'
  def new
    @event = Event.new
  end

  # Редактирование задания, внесение изменений в БД
  # @note Вызывается при нажатии по кнопке 'Edit'
  def edit
    authorize @event
    I18n.locale = session.fetch(:locale, I18n.default_locale).to_sym
  end

  # Создает новый объект, проверяет его и затем сохраняет в БД
  def create
    @event = current_user.events.create(event_params)

    respond_to do |format|
      if @event.save
        format.html { redirect_to event_url(@event), notice: 'Event was successfully created.' }
        format.json { render :show, status: :created, location: @event }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # Создание формы редактирования
  def update
    authorize @event
    respond_to do |format|
      if @event.update(event_params)
        format.html { redirect_to event_url(@event), notice: 'Event was successfully updated.' }
        format.json { render :show, status: :ok, location: @event }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # Удаление задания
  # @note Вызывается при нажатии по кнопке 'Delete'
  def destroy
    authorize @event
    @event.destroy
    respond_to do |format|
      format.html { redirect_to events_url, notice: 'Event was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Установка задания перед действием, при помощи коллбэка
  def set_event
    @event = Event.with_attached_files.find(params[:id])
  end

  # Установка списка разрешенных параметров
  def event_params
    params.require(:event).permit(:name, :content, :finished_at, :done, files: [])
  end
end

app/helpers/events_helper.rb
# frozen_string_literal: true

module EventsHelper
end

app/views/events/_event.html.slim
tr
  td = event.items.size
  td = link_to event.name.truncate(80), event, class: 'link-secondary'
  td = link_to edit_event_path(event), class: 'btn btn-secondary' do
    span.fa.fa-pencil

app/views/events/_form.html.slim
= form_for @event do |f|
  - if @event.errors.any?
    #error_explanation
      h2 = "#{pluralize(event.errors.count, 'error')} prohibited this event from being saved:"
      ul
        - event.errors.full_messages.each do |message|
          li = message

  .field
    = f.label :name, class: 'form-label'
    = f.text_field :name, class: 'form-control'

  .field
    = f.label :content, class: 'form-label'
    = f.text_area :content, class: 'form-control'

  .field
    = f.label :done, class: 'form-label'
    = f.check_box :done, class: 'form-check-input'

  .field
    = f.label :finished_at, class: 'form-label'
    = f.datetime_field :finished_at, class: 'form-control'
    
  .field
    = f.label :files, class: 'form-label'
    = f.file_field :files, multiple: true, class: 'form-control'    

  .actions
    = f.submit class: 'btn btn-secondary'

app/views/events/edit.html.slim
h1= t('label.edit')
== render 'form', event: @event
=> link_to t('label.show'), @event
'|
=< link_to t('label.back'), events_path
- language_link_name = session[:locale] == I18n.default_locale.to_s ? 'EN' : 'RU'
=< link_to language_link_name, toggle_path, method: :post

app/views/events/index.html.slim
table.table.table-striped 
  thead.table.table-dark
    tr
    th ID
    th =t('event')
    th =t('edit.edit')

  tbody
    = render partial: 'event', collection: @events, cached: true

br

ul.pagination.pagination.justify-content-end
  li.page-item
  = paginate @events, class: 'page-link'
br
p
  = link_to t('new_event'), new_event_path, class: 'btn btn-secondary' 

app/views/events/new.html.slim
h1= t('new_event')
== render 'form'

br

= link_to t('back'), events_path

app/views/events/show.html.slim
- cache @event do
  p#notice = notice

  p
    strong Name:
    = @event.name
  p
    strong Content:
    = @event.content
  p
    strong Done:
    = @event.done
  p
    strong Items:
    table
      - @event.items.order(:created_at).each_with_index do |item, i|
        - cache [item, i] do
          tr
            td = i + 1
            td = item.name
  - if @comments
    p
      strong Comments:
      - Comment.each_with_level(@comments) do |comment, level|
        p(style="padding-left:#{level * 20}px")
          = comment.content          

  - if @event.files.attached?
    p
      strong Files:
      table
        - @event.files.each_with_index do |file, i|
          - cache [file, i] do
            tr
              td = i + 1
              td = link_to file.blob.filename, rails_blob_path(file, only_path: true)

  => link_to 'Edit', edit_event_path(@event)
  '|
  =< link_to 'Back', events_path