config/routes.rb
# frozen_string_literal: true

require 'resque/server'

Rails.application.routes.draw do
  devise_for :users # , ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  mount RootApi => '/'
  mount Resque::Server.new, at: '/resque'

  resources :events do
    resources :items
  end

  get 'events/page/(:page(.:format))', to: 'events#index'

  get :toggle, to: 'locales#toggle'
  get :about, to: 'about#index'
  get :help, to: 'help#index'
  root 'events#index'
end

app/views/layouts/_navbar.slim
nav.navbar.navbar-expand-lg.bg-light
  .container-fluid
    ul
      = link_to t('navbar.home'), root_path, class: 'navbar-brand'
      = link_to t('navbar.about'), about_path, class: 'navbar-brand'
      = link_to t('navbar.help'), help_path, class: 'navbar-brand'
      - if current_user.try(:admin?)
        = link_to t('navbar.admin'), admin_root_path, class: 'navbar-brand'
      button.navbar-toggler[type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation"]

  span.navbar-toggler-icon
  #navbarSupportedContent.collapse.navbar-collapse

  ul.navbar-nav.me-auto.mb-2.mb-lg-0
    .text-center
      - if current_user_avatar?
        = image_tag current_user.avatar.variant(resize_to_limit: [50, 50]), class: 'rounded-circle'
      - else
        i.fa.fa-user style='font-size:50px'
    li.nav-item
    ul
    - if user_signed_in?
      li
        span = t('label.hello') % current_user.name
        br
        span = link_to t('label.edit'), edit_user_registration_path
        - if current_user.admin?
          span<
            |(
            = link_to(t('label.admin'), admin_root_path)
            |)
      li
        = link_to t('logout'), destroy_user_session_path, method: :delete
    - else
      li
        = link_to t('label.login'), new_user_session_path
      li
        = link_to t('label.registration'), new_user_registration_path
    ul    
    = link_to language_link_name, toggle_path, method: :post     

app/views/layouts/application.html.slim
doctype html
html
  head
    title
      | Newtodo
    meta[name="viewport" content="width=device-width,initial-scale=1"]
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag 'application', media: 'all'
    = javascript_importmap_tags 'application'
  body
    .container
      .row
        =render 'layouts/navbar'
        = yield